<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>Omtv Api</Title>
        <Description>Interface project for Omtv (One More Table Visualizer)</Description>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

</Project>
