<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Title>Omtv Html Output</Title>
        <Description>Html visualizer for Omtv (One More Table Visualizer)</Description>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Omtv.Api\Omtv.Api.csproj" />
    </ItemGroup>
</Project>
