name: Nuget

on:
  release:
    types: [created]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Omtv.Api
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: Omtv.Api/Omtv.Api.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}
    - name: Publish Omtv.Engine
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: Omtv.Engine/Omtv.Engine.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}
    - name: Publish Omtv.Csv
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: Omtv.Csv/Omtv.Csv.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}
    - name: Publish Omtv.Html
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: Omtv.Html/Omtv.Html.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}
    - name: Publish Omtv.Excel
      uses: alirezanet/publish-nuget@v3.0.4
      with:
          PROJECT_FILE_PATH: Omtv.Excel/Omtv.Excel.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}
